#!/bin/bash

INIT="$(ps --no-headers -o comm 1)"

if [ "$(id -u)" != "0" ]; then
    echo "Please run with 'sudo': sudo cancel-rename USER" >&2
    exit 1
fi

if [ "$(raspi-config nonint get_boot_cli)" -ne 0 ]; then
    if [ "$1" = "root" ] || ! getent passwd "$1" >/dev/null; then
        echo "Please specify default user: sudo cancel-rename USER" >&2
        exit 1
    fi
    IMG_VER="$(grep -s -m1 -o '[[:digit:]]\{4\}-[[:digit:]]\{2\}-[[:digit:]]\{2\}' /etc/rpi-issue)"
    if [ -f /var/lib/userconf-pi/autologin ] || [ "$IMG_VER" == "2022-04-04" ]; then
        SUDO_USER="$1" raspi-config nonint do_boot_behaviour B4
    else
        SUDO_USER="$1" raspi-config nonint do_boot_behaviour B3
    fi

    # remove the autostart for the wizard
    rm -f /etc/xdg/autostart/piwiz.desktop

    # set up a self-deleting service to delete the wizard user
    cat <<- 'EOF' > /etc/systemd/system/del-wizard.service
	[Unit]
	Description=Delete rpi-first-boot-wizard user
	After=multi-user.target
	StartLimitIntervalSec=0

	[Service]
	Type=oneshot
	RemainAfterExit=no
	ExecStartPre=/usr/bin/sleep 30
	ExecStart=/usr/sbin/userdel -r rpi-first-boot-wizard
	ExecStartPost=/usr/bin/rm -f /etc/sudoers.d/010_wiz-nopasswd
	ExecStartPost=/usr/bin/systemctl disable del-wizard.service
	ExecStartPost=/usr/bin/rm -f /etc/systemd/system/del-wizard.service
	ExecStartPost=/usr/bin/systemctl daemon-reload
	SuccessExitStatus=6
	Restart=on-failure
	RestartSec=30

	[Install]
	WantedBy=multi-user.target
	EOF
    systemctl enable --now --no-block del-wizard.service
else
    if [ -f /var/lib/userconf-pi/autologin ]; then
        SUDO_USER="$1" raspi-config nonint do_boot_behaviour B2
    else
        SUDO_USER="$1" raspi-config nonint do_boot_behaviour B1
    fi
fi

rm -f /var/lib/userconf-pi/autologin
rm -f /etc/ssh/sshd_config.d/rename_user.conf

systemctl --quiet disable userconfig
systemctl --quiet enable getty@tty1

if [ "$INIT" = "systemd" ]; then
    if systemctl --quiet is-active ssh; then
        systemctl --quiet reload ssh
    fi
    systemctl --quiet --no-block start getty@tty1
fi
