#!/bin/sh

# rename the pi user
usermod --login $1 --home /home/$1 --move-home pi
groupmod --new-name $1 pi

# set the password
echo "$1:$2" | chpasswd -e

# add to no-password
mv /etc/sudoers.d/010_pi-nopasswd "/etc/sudoers.d/010_$1-nopasswd"
sed "/etc/sudoers.d/010_$1-nopasswd" -i -e "s/pi/$1/"

# set up autologin
cat > /etc/systemd/system/getty@tty1.service.d/autologin.conf << EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin $1 --noclear %I \$TERM
EOF
sed /etc/lightdm/lightdm.conf -i -e "s/^\(#\|\)autologin-user=.*/autologin-user=$1/"

# delete sudo script
rm /etc/sudoers.d/010_lightdm
